const storageKey="financeTrackerPwaV2";
const knownKeys=["financeTrackerPwaV2","personalFinanceTrackerV1","myFinance","myFinanceV4","myFinanceV5","myFinanceV6"];
const today=new Date().toISOString().slice(0,10);
const basicTax=.20;
let editAccountId=null, editCostId=null;
const meta={"Current account":{c:"#2563eb",i:"💳",t:false},"Savings":{c:"#16a34a",i:"🏦",t:false},"Cash ISA":{c:"#0891b2",i:"🛡️",t:true},"Stocks and shares ISA":{c:"#7c3aed",i:"📈",t:true},"Premium Bonds":{c:"#f97316",i:"🎟️",t:true},"Pension":{c:"#1e3a8a",i:"👴",t:true},"Investment":{c:"#9333ea",i:"📊",t:false},"Property":{c:"#92400e",i:"🏠",t:true},"Other":{c:"#64748b",i:"➕",t:false}};
function id(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function blank(){return{accounts:[],spending:[],costs:[],snapshots:[],preferences:{darkMode:false}}}
function parse(v){try{return JSON.parse(v)}catch{return null}}
function defTax(t){return (meta[t]||meta.Other).t}
function norm(x){x=x&&x.data?x.data:x;if(!x||typeof x!=="object")return blank();return{accounts:Array.isArray(x.accounts)?x.accounts.map(a=>({id:a.id||id(),name:a.name||"Unnamed account",owner:a.owner||"Me",type:a.type||"Other",balance:Number(a.balance||0),rate:Number(a.rate||0),monthlyContribution:Number(a.monthlyContribution||0),monthlyWithdrawal:Number(a.monthlyWithdrawal||0),taxFree:a.taxFree??defTax(a.type||"Other")})):[],spending:Array.isArray(x.spending)?x.spending.map(s=>({id:s.id||id(),date:s.date||today,category:s.category||"Other",amount:Number(s.amount||0),note:s.note||""})):[],costs:Array.isArray(x.costs)?x.costs.map(c=>({id:c.id||id(),name:c.name||"Regular spending",category:c.category||"Other",amount:Number(c.amount||0)})):[],snapshots:Array.isArray(x.snapshots)?x.snapshots.map(s=>({id:s.id||id(),date:s.date||today,total:Number(s.total||0)})):[],preferences:x.preferences||{darkMode:false}}}
function score(s){return s.accounts.length*1000+s.spending.length*10+s.costs.length+s.snapshots.length}
function load(){let best=blank(),bestKey="none",bestScore=-1;knownKeys.forEach(k=>{const s=norm(parse(localStorage.getItem(k)));const sc=score(s);if(sc>bestScore){best=s;bestKey=k;bestScore=sc}});window.recoveryMsg=bestScore>0?`Recovered ${best.accounts.length} account(s), ${best.spending.length} spending entr${best.spending.length===1?"y":"ies"} and ${best.snapshots.length} snapshot(s) from ${bestKey}.`:"No existing finance data found in browser storage.";localStorage.setItem(storageKey,JSON.stringify(best));return best}
let state=load();
function save(){localStorage.setItem(storageKey,JSON.stringify(state))}
function money(v){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:0}).format(v||0)}
function esc(t){return String(t).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function applyPrefs(){document.body.classList.toggle("dark",!!state.preferences.darkMode);darkBtn.textContent=state.preferences.darkMode?"Light mode":"Dark mode"}
function toggleDarkMode(){state.preferences.darkMode=!state.preferences.darkMode;save();applyPrefs();render()}
function tab(id,btn){document.querySelectorAll("section").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".navbtn").forEach(b=>b.classList.remove("active"));btn.classList.add("active");render()}
function total(){return state.accounts.reduce((s,a)=>s+Number(a.balance||0),0)}
function byType(t){return state.accounts.filter(a=>a.type===t).reduce((s,a)=>s+Number(a.balance||0),0)}
function regular(){return state.costs.reduce((s,c)=>s+Number(c.amount||0),0)}
function contrib(){return state.accounts.reduce((s,a)=>s+Number(a.monthlyContribution||0)-Number(a.monthlyWithdrawal||0),0)}
function forecast(months){let bals=state.accounts.map(a=>({...a})),points=[],tax=0,costs=regular();for(let m=0;m<=months;m++){points.push(bals.reduce((s,a)=>s+Number(a.balance||0),0));if(m===months)break;let spendable=bals.filter(a=>a.type!=="Property"&&a.type!=="Pension"),share=spendable.length?costs/spendable.length:0;bals=bals.map(a=>{let r=Math.pow(1+Number(a.rate||0)/100,1/12)-1,g=Number(a.balance||0)*r,t=a.taxFree?0:Math.max(0,g*basicTax),cost=(a.type!=="Property"&&a.type!=="Pension")?share:0;tax+=t;let next=Number(a.balance||0)+g-t+Number(a.monthlyContribution||0)-Number(a.monthlyWithdrawal||0)-cost;return{...a,balance:Math.max(0,next)}})}return{points,tax}}
function defaultTax(){if(editAccountId)return;aTax.value=String(defTax(aType.value))}
function saveAccount(){let data={name:aName.value.trim(),owner:aOwner.value,type:aType.value,balance:Number(aBalance.value),rate:Number(aRate.value||0),monthlyContribution:Number(aContrib.value||0),monthlyWithdrawal:Number(aWithdraw.value||0),taxFree:aTax.value==="true"};if(!data.name||Number.isNaN(data.balance)){alert("Please add a name and balance.");return}if(editAccountId)state.accounts=state.accounts.map(a=>a.id===editAccountId?{...a,...data}:a);else state.accounts.push({id:id(),...data});cancelAccount();save();render()}
function editAccount(x){let a=state.accounts.find(a=>a.id===x);if(!a)return;editAccountId=x;aName.value=a.name||"";aOwner.value=a.owner||"Me";aType.value=a.type||"Other";aBalance.value=a.balance??"";aRate.value=a.rate??"";aContrib.value=a.monthlyContribution??"";aWithdraw.value=a.monthlyWithdrawal??"";aTax.value=String(a.taxFree??defTax(a.type));aSave.textContent="Save changes";aCancel.style.display="inline-block";document.querySelectorAll("section").forEach(s=>s.classList.remove("active"));accounts.classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function cancelAccount(){editAccountId=null;[aName,aBalance,aRate,aContrib,aWithdraw].forEach(e=>e.value="");aOwner.value="Me";aType.value="Current account";aTax.value=String(defTax("Current account"));aSave.textContent="Add account";aCancel.style.display="none"}
function deleteAccount(x){if(!confirm("Delete this account?"))return;state.accounts=state.accounts.filter(a=>a.id!==x);save();render()}
function saveCost(){let data={name:cName.value.trim(),category:cCat.value,amount:Number(cAmount.value)};if(!data.name||Number.isNaN(data.amount)||data.amount<=0){alert("Please add a regular spending name and amount.");return}if(editCostId)state.costs=state.costs.map(c=>c.id===editCostId?{...c,...data}:c);else state.costs.push({id:id(),...data});cancelCost();save();render()}
function editCost(x){let c=state.costs.find(c=>c.id===x);if(!c)return;editCostId=x;cName.value=c.name;cCat.value=c.category;cAmount.value=c.amount;cSave.textContent="Save changes";cCancel.style.display="inline-block"}
function cancelCost(){editCostId=null;cName.value="";cCat.value="Food";cAmount.value="";cSave.textContent="Add regular spending";cCancel.style.display="none"}
function deleteCost(x){if(!confirm("Delete this regular spending item?"))return;state.costs=state.costs.filter(c=>c.id!==x);save();render()}
function addSpending(){let amount=Number(sAmount.value);if(Number.isNaN(amount)||amount<=0){alert("Please add a spending amount.");return}state.spending.push({id:id(),date:sDate.value||today,category:sCat.value,amount,note:sNote.value.trim()});sAmount.value="";sNote.value="";save();render()}
function deleteSpending(x){state.spending=state.spending.filter(s=>s.id!==x);save();render()}
function snapshot(){let e=state.snapshots.find(s=>s.date===today);if(e){if(!confirm("Replace today's snapshot?"))return;e.total=total()}else state.snapshots.push({id:id(),date:today,total:total()});state.snapshots.sort((a,b)=>a.date.localeCompare(b.date));save();render()}
function deleteLastSnapshot(){if(!state.snapshots.length)return;if(!confirm("Delete latest snapshot?"))return;state.snapshots.pop();save();render()}
function exportData(){let blob=new Blob([JSON.stringify({app:"My Finance",version:7,exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`my-finance-backup-${today}.json`;a.click();URL.revokeObjectURL(url)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{let n=norm(parse(r.result));if(!n.accounts.length&&!n.spending.length){alert("No finance data found.");return}if(confirm("Replace current My Finance data?")){state=n;save();applyPrefs();render();alert("Backup imported.")}};r.readAsText(f)}
function renderDashboard(){let t=total(),f=forecast(12);netWorth.textContent=money(t);liquid.textContent=money(t-byType("Property"));regularTotal.textContent=money(regular());projection12.textContent=money(f.points.at(-1)||0);monthlyContrib.textContent=money(contrib());monthlySpendDeducted.textContent=money(regular());tax12.textContent=money(f.tax);notice.innerHTML=`<strong>Recovery status</strong><p class="small">${esc(window.recoveryMsg)}</p><button class="secondary" onclick="exportData()">Download backup now</button>`}
function renderAllocation(){let t=total(),groups={};state.accounts.forEach(a=>groups[a.type]=(groups[a.type]||0)+Number(a.balance||0));let entries=Object.entries(groups).sort((a,b)=>b[1]-a[1]);allocation.innerHTML=entries.length?entries.map(([type,value])=>{let m=meta[type]||meta.Other,p=t?value/t*100:0;return`<div><span class="badge" style="background:${m.c}">${m.i} ${esc(type)}</span><strong style="float:right">${money(value)}</strong><div class="barwrap"><div class="bar" style="width:${p}%;background:${m.c}"></div></div><div class="small">${p.toFixed(1)}% of net worth</div></div>`}).join(""):'<div class="empty">No accounts added yet.</div>'}
function renderAccounts(){accountsTable.innerHTML=state.accounts.length?`<table><thead><tr><th>Name</th><th>Owner</th><th>Type</th><th>Balance</th><th></th></tr></thead><tbody>${state.accounts.map(a=>{let m=meta[a.type]||meta.Other;return`<tr><td><strong>${esc(a.name)}</strong><br><span class="small">Rate: ${Number(a.rate||0).toFixed(2)}% · Monthly net: ${money(Number(a.monthlyContribution||0)-Number(a.monthlyWithdrawal||0))}</span></td><td>${esc(a.owner||"Me")}</td><td><span class="badge" style="background:${m.c}">${m.i} ${esc(a.type)}</span><br><span class="small">${a.taxFree?"Tax free":"20% tax"}</span></td><td>${money(a.balance)}</td><td><div class="rowbtns"><button class="secondary" onclick="editAccount('${a.id}')">Edit</button><button class="danger" onclick="deleteAccount('${a.id}')">Delete</button></div></td></tr>`}).join("")}</tbody></table>`:'<div class="empty">No accounts added yet.</div>'}
function renderCosts(){costsTable.innerHTML=state.costs.length?`<table><thead><tr><th>Name</th><th>Category</th><th>Amount</th><th></th></tr></thead><tbody>${state.costs.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.category)}</td><td>${money(c.amount)}</td><td><div class="rowbtns"><button class="secondary" onclick="editCost('${c.id}')">Edit</button><button class="danger" onclick="deleteCost('${c.id}')">Delete</button></div></td></tr>`).join("")}</tbody></table><p class="small"><strong>Total:</strong> ${money(regular())}</p>`:'<div class="empty">No regular monthly spending added yet.</div>'}
function renderSpending(){let items=[...state.spending].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,50);spendingTable.innerHTML=items.length?`<table><thead><tr><th>Date</th><th>Category</th><th>Note</th><th>Amount</th><th></th></tr></thead><tbody>${items.map(s=>`<tr><td>${esc(s.date)}</td><td>${esc(s.category)}</td><td>${esc(s.note||"")}</td><td>${money(s.amount)}</td><td><button class="danger" onclick="deleteSpending('${s.id}')">Delete</button></td></tr>`).join("")}</tbody></table>`:'<div class="empty">No actual spending added yet.</div>'}
function renderForecast(){let y=Math.max(1,Math.min(40,Number(years.value||10))),r=forecast(y*12),start=r.points[0]||0,end=r.points.at(-1)||0,inf=Number(inflation.value||0)/100,real=end/Math.pow(1+inf,y);forecastSummary.innerHTML=`<table><tbody><tr><th>Starting net worth</th><td>${money(start)}</td></tr><tr><th>Projected net worth after ${y} years</th><td>${money(end)}</td></tr><tr><th>Regular spending deducted</th><td>${money(regular()*y*12)}</td></tr><tr><th>Estimated tax deducted</th><td>${money(r.tax)}</td></tr><tr><th>Change</th><td>${money(end-start)}</td></tr><tr><th>Inflation-adjusted estimate</th><td>${money(real)}</td></tr></tbody></table>`}
function canvas(id){let cv=document.getElementById(id),ratio=devicePixelRatio||1,rect=cv.getBoundingClientRect();cv.width=rect.width*ratio;cv.height=rect.height*ratio;let ctx=cv.getContext("2d");ctx.scale(ratio,ratio);return{ctx,rect}}
function line(id,points){let {ctx,rect}=canvas(id);ctx.clearRect(0,0,rect.width,rect.height);if(!points.length||Math.max(...points)<=0){ctx.fillStyle="#667085";ctx.fillText("No data yet",rect.width/2-35,110);return}let p=36,min=Math.min(...points),max=Math.max(...points),range=max-min||1;ctx.strokeStyle="#2563eb";ctx.lineWidth=4;ctx.beginPath();points.forEach((v,i)=>{let x=p+i/Math.max(1,points.length-1)*(rect.width-p*2),y=rect.height-p-(v-min)/range*(rect.height-p*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle="#667085";ctx.font="12px system-ui";ctx.fillText(money(max),p,20);ctx.fillText(money(min),p,rect.height-10)}
function bars(id,groups){let labels=Object.keys(groups),values=Object.values(groups),{ctx,rect}=canvas(id);ctx.clearRect(0,0,rect.width,rect.height);if(!values.length||Math.max(...values)<=0){ctx.fillStyle="#667085";ctx.fillText("No data yet",rect.width/2-35,110);return}let p=36,max=Math.max(...values),bw=(rect.width-p*2)/values.length*.65;values.forEach((v,i)=>{let x=p+i*((rect.width-p*2)/values.length)+bw*.25,h=v/max*(rect.height-p*2);ctx.fillStyle="#2563eb";ctx.fillRect(x,rect.height-p-h,bw,h);ctx.fillStyle="#667085";ctx.font="12px system-ui";ctx.save();ctx.translate(x+bw/2,rect.height-8);ctx.rotate(-.35);ctx.textAlign="right";ctx.fillText(labels[i].slice(0,16),0,0);ctx.restore()})}
function renderCharts(){let ym=new Date().toISOString().slice(0,7),g={};state.spending.filter(s=>String(s.date).slice(0,7)===ym).forEach(s=>g[s.category]=(g[s.category]||0)+Number(s.amount||0));bars("spendChart",g);line("snapshotChart",state.snapshots.map(s=>s.total));let y=Math.max(1,Math.min(40,Number(years.value||10)));line("longChart",forecast(y*12).points.filter((_,i)=>i%12===0))}
function render(){try{renderDashboard();renderAllocation();renderAccounts();renderCosts();renderSpending();renderForecast();setTimeout(renderCharts,20)}catch(e){notice.innerHTML=`<strong>Display error</strong><p class="small">${esc(e.message)}</p><button class="secondary" onclick="exportData()">Download backup</button>`}}
if(sDate)sDate.value=today;applyPrefs();defaultTax();save();render();window.addEventListener("resize",renderCharts);
